url: http://effogroup.com
baseurl: 

# Site settings
title: EffoGroup
email: contact@mlsuho.me
description: "Welcome to EffoGroup. Let's build business together."


# Team names, titles and social links
people:
- name: Hieu Ho V.
  pic: hieu-ho
  position: Founder
  social:
    - title: twitter
      url: https://twitter.com/hovanhieu0509
    - title: facebook
      url: https://www.facebook.com/bida.ho
    - title: linkedin
      url: https://www.linkedin.com/in/bidaho/
- name: Su Ho V.
  pic: su-ho
  position: Co-Founder
  social:
    - title: twitter
      url: https://twitter.com/mlsuho
    - title: facebook
      url: https://www.facebook.com/mlsuho
    - title: linkedin
      url: https://www.linkedin.com/in/mlsuho/
    - title: github
      url: https://www.github.com/mlsuho
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EffoGroup-1237921399715561/
  - title: phone
    url: tel:+84935307484

# Postal address (add as many lines as necessary)
address:
  - line: Phu Thuan, Phu Vang
  - line: Thua Thien Hue

# Build settings
markdown: kramdown
permalink: pretty